export const ErrorCode = {
  // Auth
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  PHONE_ALREADY_REGISTERED: 'PHONE_ALREADY_REGISTERED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ALREADY_AN_EXPERT: 'ALREADY_AN_EXPERT',
  ADMINS_CANNOT_CHANGE_ROLE: 'ADMINS_CANNOT_CHANGE_ROLE',
  CANNOT_REVERT_AFTER_ONBOARDING: 'CANNOT_REVERT_AFTER_ONBOARDING',
  NO_DRAFT_PROFILE_TO_ABANDON: 'NO_DRAFT_PROFILE_TO_ABANDON',

  // Expert Profile
  EXPERT_PROFILE_ALREADY_EXISTS: 'EXPERT_PROFILE_ALREADY_EXISTS',
  SLUG_ALREADY_TAKEN: 'SLUG_ALREADY_TAKEN',
  SLUG_RESERVED: 'SLUG_RESERVED',
  SLUG_NOT_AVAILABLE: 'SLUG_NOT_AVAILABLE',
  EXPERT_NOT_FOUND: 'EXPERT_NOT_FOUND',
  EXPERT_PROFILE_NOT_FOUND: 'EXPERT_PROFILE_NOT_FOUND',
  ADMINS_CANNOT_CREATE_PROFILE: 'ADMINS_CANNOT_CREATE_PROFILE',
  ONBOARDING_ALREADY_COMPLETED: 'ONBOARDING_ALREADY_COMPLETED',
  COMPLETE_STEP_1_FIRST: 'COMPLETE_STEP_1_FIRST',
  COMPLETE_STEP_2_FIRST: 'COMPLETE_STEP_2_FIRST',
  COMPLETE_STEP_3_FIRST: 'COMPLETE_STEP_3_FIRST',
  MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',

  // Booking
  CANNOT_BOOK_YOURSELF: 'CANNOT_BOOK_YOURSELF',
  CANNOT_BOOK_IN_PAST: 'CANNOT_BOOK_IN_PAST',
  TIME_SLOT_ALREADY_BOOKED: 'TIME_SLOT_ALREADY_BOOKED',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  ONLY_CLIENT_CAN_CONFIRM_PAYMENT: 'ONLY_CLIENT_CAN_CONFIRM_PAYMENT',
  BOOKING_NOT_AWAITING_PAYMENT: 'BOOKING_NOT_AWAITING_PAYMENT',
  PAYMENT_RECORDING_FAILED: 'PAYMENT_RECORDING_FAILED',

  // Availability
  INVALID_DATE_PARAMETERS: 'INVALID_DATE_PARAMETERS',
  DATE_RANGE_TOO_LARGE: 'DATE_RANGE_TOO_LARGE',

  // Payment
  INVALID_WEBHOOK_SIGNATURE: 'INVALID_WEBHOOK_SIGNATURE',

  // Generic
  FORBIDDEN: 'FORBIDDEN',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
