import { ExpertCategory } from '../enums/expert-category.enum';

/** Curated skill set grouped by expert category */
export const SKILLS_BY_CATEGORY: Record<ExpertCategory, string[]> = {
  [ExpertCategory.FITNESS]: [
    'yoga',
    'pilates',
    'strength training',
    'weight loss',
    'muscle building',
    'hiit',
    'crossfit',
    'stretching',
    'mobility',
    'calisthenics',
    'boxing',
    'kickboxing',
    'martial arts',
    'running coaching',
    'marathon training',
    'swimming coaching',
    'bodybuilding',
    'posture correction',
    'injury rehabilitation',
    'prenatal fitness',
    'postnatal fitness',
    'senior fitness',
    'functional training',
    'sports performance',
    'flexibility',
    'meditation',
    'breathwork',
    'dance fitness',
    'zumba',
    'aerobics',
    'personal training',
    'group fitness',
    'boot camp',
    'kettlebell training',
    'trx suspension',
    'barre',
    'tai chi',
    'qigong',
  ],

  [ExpertCategory.EDUCATION]: [
    'mathematics',
    'physics',
    'chemistry',
    'biology',
    'computer science',
    'algebra',
    'calculus',
    'geometry',
    'statistics',
    'trigonometry',
    'french literature',
    'arabic literature',
    'english literature',
    'philosophy',
    'history',
    'geography',
    'economics',
    'essay writing',
    'creative writing',
    'academic writing',
    'research methodology',
    'thesis supervision',
    'exam preparation',
    'baccalaureate prep',
    'university tutoring',
    'primary school tutoring',
    'middle school tutoring',
    'high school tutoring',
    'study skills',
    'speed reading',
    'public speaking',
    'debate coaching',
    'science olympiad',
    'robotics education',
    'stem education',
    'special education',
    'learning disabilities support',
    'gifted student mentoring',
  ],

  [ExpertCategory.MEDICINE]: [
    'wellness coaching',
    'health consulting',
    'preventive care',
    'stress management',
    'sleep improvement',
    'chronic pain management',
    'physiotherapy guidance',
    'ergonomics',
    'first aid training',
    'mental health awareness',
    'health education',
    'lifestyle medicine',
    'holistic wellness',
    'rehabilitation guidance',
    'occupational health',
    'public health education',
  ],

  [ExpertCategory.LAW]: [
    'business law',
    'commercial law',
    'contract law',
    'labor law',
    'employment law',
    'family law',
    'real estate law',
    'property law',
    'intellectual property',
    'trademark registration',
    'patent law',
    'corporate law',
    'tax law',
    'immigration law',
    'criminal law',
    'civil litigation',
    'mediation',
    'arbitration',
    'legal consulting',
    'startup legal advice',
    'data privacy law',
    'gdpr compliance',
    'consumer protection',
    'inheritance law',
    'international trade law',
    'customs law',
    'banking law',
    'insurance law',
    'environmental law',
    'administrative law',
  ],

  [ExpertCategory.BUSINESS]: [
    'business strategy',
    'startup consulting',
    'business plan writing',
    'entrepreneurship',
    'lean startup',
    'product management',
    'project management',
    'agile coaching',
    'scrum mastery',
    'operations management',
    'supply chain management',
    'sales strategy',
    'b2b sales',
    'negotiation skills',
    'leadership coaching',
    'executive coaching',
    'team management',
    'change management',
    'crisis management',
    'hr consulting',
    'talent acquisition',
    'employee engagement',
    'performance management',
    'organizational development',
    'market research',
    'competitive analysis',
    'brand strategy',
    'digital marketing',
    'content marketing',
    'social media marketing',
    'seo',
    'sem',
    'email marketing',
    'growth hacking',
    'public relations',
    'customer experience',
    'e-commerce strategy',
    'franchise consulting',
    'international business',
    'export consulting',
  ],

  [ExpertCategory.TECHNOLOGY]: [
    'web development',
    'frontend development',
    'backend development',
    'full-stack development',
    'react',
    'angular',
    'vue.js',
    'next.js',
    'node.js',
    'python',
    'java',
    'c++',
    'golang',
    'rust',
    'typescript',
    'javascript',
    'mobile development',
    'ios development',
    'android development',
    'flutter',
    'react native',
    'devops',
    'cloud computing',
    'aws',
    'azure',
    'google cloud',
    'docker',
    'kubernetes',
    'ci/cd',
    'database design',
    'sql',
    'mongodb',
    'postgresql',
    'data engineering',
    'data science',
    'machine learning',
    'deep learning',
    'artificial intelligence',
    'nlp',
    'computer vision',
    'cybersecurity',
    'penetration testing',
    'network security',
    'blockchain',
    'smart contracts',
    'ui/ux design',
    'figma',
    'system design',
    'software architecture',
    'api design',
    'microservices',
    'game development',
    'unity',
    'embedded systems',
    'iot',
    'linux administration',
    'git',
    'technical writing',
    'code review',
    'mentoring junior devs',
  ],

  [ExpertCategory.PSYCHOLOGY]: [
    'life coaching',
    'career coaching',
    'relationship coaching',
    'stress management',
    'anxiety management',
    'self-confidence building',
    'self-esteem',
    'emotional intelligence',
    'anger management',
    'grief counseling',
    'trauma support',
    'mindfulness',
    'cognitive behavioral techniques',
    'positive psychology',
    'motivation coaching',
    'habit formation',
    'addiction support',
    'parenting guidance',
    'child psychology education',
    'adolescent support',
    'couples coaching',
    'family dynamics',
    'work-life balance',
    'burnout prevention',
    'personal development',
    'goal setting',
    'time management',
    'procrastination',
    'social skills',
    'communication skills',
    'assertiveness training',
    'conflict resolution',
    'resilience building',
  ],

  [ExpertCategory.NUTRITION]: [
    'weight management',
    'meal planning',
    'sports nutrition',
    'vegan nutrition',
    'vegetarian nutrition',
    'keto diet',
    'intermittent fasting',
    'calorie counting',
    'macro tracking',
    'gut health',
    'food allergies',
    'food intolerance',
    'diabetes nutrition',
    'heart-healthy eating',
    'prenatal nutrition',
    'postnatal nutrition',
    'child nutrition',
    'senior nutrition',
    'eating disorder recovery support',
    'anti-inflammatory diet',
    'mediterranean diet',
    'clean eating',
    'supplement guidance',
    'hydration coaching',
    'intuitive eating',
    'body composition',
    'healthy cooking',
    'meal prep coaching',
  ],

  [ExpertCategory.FINANCE]: [
    'personal finance',
    'budgeting',
    'saving strategies',
    'investment basics',
    'stock market',
    'cryptocurrency',
    'real estate investing',
    'retirement planning',
    'financial planning',
    'debt management',
    'credit score improvement',
    'tax planning',
    'tax filing',
    'bookkeeping',
    'accounting',
    'financial modeling',
    'business valuation',
    'fundraising',
    'venture capital',
    'angel investing',
    'crowdfunding',
    'forex trading',
    'options trading',
    'portfolio management',
    'risk management',
    'insurance planning',
    'estate planning',
    'wealth management',
    'financial literacy education',
    'startup finance',
  ],

  [ExpertCategory.LANGUAGES]: [
    'french',
    'english',
    'arabic',
    'german',
    'spanish',
    'italian',
    'portuguese',
    'turkish',
    'chinese mandarin',
    'japanese',
    'korean',
    'russian',
    'dutch',
    'swedish',
    'conversational practice',
    'business language',
    'academic language',
    'pronunciation coaching',
    'accent reduction',
    'grammar',
    'vocabulary building',
    'reading comprehension',
    'writing skills',
    'listening comprehension',
    'exam prep ielts',
    'exam prep toefl',
    'exam prep delf',
    'exam prep tcf',
    'translation',
    'interpretation',
    'language for kids',
    'sign language',
  ],

  [ExpertCategory.MUSIC]: [
    'piano',
    'guitar',
    'acoustic guitar',
    'electric guitar',
    'bass guitar',
    'violin',
    'cello',
    'drums',
    'percussion',
    'flute',
    'saxophone',
    'trumpet',
    'clarinet',
    'oud',
    'qanun',
    'darbuka',
    'singing',
    'vocal coaching',
    'music theory',
    'sight reading',
    'ear training',
    'songwriting',
    'music composition',
    'music production',
    'mixing and mastering',
    'ableton live',
    'logic pro',
    'fl studio',
    'sound design',
    'dj skills',
    'beatmaking',
    'rap',
    'opera singing',
    'choir conducting',
    'music for kids',
    'classical music',
    'jazz',
    'arabic music',
    'maqam',
  ],

  [ExpertCategory.ART]: [
    'drawing',
    'sketching',
    'pencil drawing',
    'charcoal drawing',
    'oil painting',
    'watercolor painting',
    'acrylic painting',
    'digital painting',
    'digital illustration',
    'graphic design',
    'logo design',
    'brand identity design',
    'typography',
    'calligraphy',
    'arabic calligraphy',
    'photography',
    'portrait photography',
    'landscape photography',
    'product photography',
    'photo editing',
    'lightroom',
    'photoshop',
    'video editing',
    'filmmaking',
    'animation',
    '2d animation',
    '3d modeling',
    'blender',
    'sculpture',
    'pottery',
    'ceramics',
    'interior design',
    'fashion design',
    'jewelry design',
    'hand lettering',
    'comic art',
    'manga drawing',
    'concept art',
    'art history',
    'art therapy',
    'craft making',
    'embroidery',
    'woodworking',
  ],

  [ExpertCategory.OTHER]: [
    'career counseling',
    'resume writing',
    'interview preparation',
    'linkedin optimization',
    'personal branding',
    'public speaking',
    'presentation skills',
    'event planning',
    'wedding planning',
    'travel planning',
    'relocation consulting',
    'home organization',
    'decluttering',
    'productivity coaching',
    'sustainability consulting',
    'gardening',
    'pet training',
    'cooking classes',
    'baking',
    'pastry making',
    'wine tasting',
    'coffee expertise',
    'astrology',
    'tarot reading',
    'chess coaching',
    'esports coaching',
    'gaming strategy',
    'diy home improvement',
    'car maintenance basics',
    'sewing',
    'knitting',
  ],
};

/** Flat array of all skills (deduplicated) */
export const ALL_SKILLS: string[] = [
  ...new Set(
    Object.values(SKILLS_BY_CATEGORY).flat(),
  ),
];

/** Get skills for a specific category, optionally filtered by search query */
export function getSkillsForCategory(
  category: ExpertCategory,
  query?: string,
): string[] {
  const skills = SKILLS_BY_CATEGORY[category] || [];
  if (!query) return skills;
  const q = query.trim().toLowerCase();
  return skills.filter((s) => s.includes(q));
}

/** Search across all skills regardless of category */
export function searchAllSkills(query: string, limit = 20): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return ALL_SKILLS.filter((s) => s.includes(q)).slice(0, limit);
}
