export enum BookingStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED_BY_CLIENT = 'CANCELLED_BY_CLIENT',
  CANCELLED_BY_EXPERT = 'CANCELLED_BY_EXPERT',
  NO_SHOW = 'NO_SHOW',
  DISPUTED = 'DISPUTED',
}
