export enum PaymentStatus {
  PENDING = 'PENDING',
  CAPTURED = 'CAPTURED',
  RELEASED = 'RELEASED',
  REFUNDED_FULL = 'REFUNDED_FULL',
  REFUNDED_PARTIAL = 'REFUNDED_PARTIAL',
  PENDING_REFUND = 'PENDING_REFUND',
  FAILED = 'FAILED',
}
