export enum PaymentStatus {
  PENDING = 'PENDING',
  CAPTURED = 'CAPTURED',
  HELD = 'HELD',
  RELEASED = 'RELEASED',
  REFUNDED_FULL = 'REFUNDED_FULL',
  REFUNDED_PARTIAL = 'REFUNDED_PARTIAL',
  FAILED = 'FAILED',
}
